import type { IndustryDetail } from './api';

export const FALLBACK_INDUSTRIES: IndustryDetail[] = [
  {
    id: 'fb-retail',
    name: 'Retail',
    slug: 'retail',
    shortDescription: 'Systems for business that moves fast.',
    businessContext: 'Retail businesses need systems that keep sales, stock and payments moving together through busy trading hours.',
    challengeHeadline: 'OPERATIONS\nBECOME\nFRAGMENTED.',
    challenge: 'When checkout, inventory and customer records live in separate tools, teams lose visibility and speed at the moments that matter most.',
    systemDescription: 'Novaflow builds retail systems that connect the daily flow of products, sales and payments.',
    systemItems: ['POS', 'Inventory', 'Payments', 'Customers', 'Operations'],
    status: 'published',
    order: 1,
    visual: null,
    mobileVisual: null,
    relatedProductItems: [
      {
        id: 'fp-techlane',
        name: 'TechLane',
        slug: 'techlane',
        category: 'POS / Business Operations',
        shortDescription: 'A POS and business operations system built around daily sales and inventory workflows.',
        hero: null,
      },
    ],
    capabilityItems: [],
    relatedCaseStudies: [],
    seo: null,
  },
  {
    id: 'fb-pharmacy',
    name: 'Pharmacy',
    slug: 'pharmacy',
    shortDescription: 'Systems for stock, dispensing and daily pharmacy operations.',
    businessContext: 'Pharmacy teams manage regulated stock, dispensing workflows and customer service under constant time pressure.',
    challengeHeadline: 'STOCK AND\nSERVICE\nSPLIT APART.',
    challenge: 'Prescription queues, expiry tracking and sales often depend on disconnected processes that make daily operations harder to control.',
    systemDescription: 'Novaflow can build pharmacy operations software around stock control, dispensing and point-of-sale workflows.',
    systemItems: ['POS', 'Inventory', 'Expiry', 'Prescriptions', 'Customers'],
    status: 'published',
    order: 2,
    visual: null,
    mobileVisual: null,
    relatedProductItems: [],
    capabilityItems: [],
    relatedCaseStudies: [],
    seo: null,
  },
  {
    id: 'fb-isp',
    name: 'ISP',
    slug: 'isp',
    shortDescription: 'Systems for subscribers, billing and network operations.',
    businessContext: 'ISPs coordinate subscribers, service plans, billing cycles and network activity across growing customer bases.',
    challengeHeadline: 'BILLING AND\nOPERATIONS\nDRIFT APART.',
    challenge: 'Subscriber records, invoicing and network workflows can become difficult to manage when they are handled through separate systems.',
    systemDescription: 'Novaflow builds ISP systems that connect billing, subscribers, payments and operational visibility.',
    systemItems: ['Billing', 'Subscribers', 'Payments', 'Packages', 'Network'],
    status: 'published',
    order: 3,
    visual: null,
    mobileVisual: null,
    relatedProductItems: [
      {
        id: 'fp-bytepesa',
        name: 'BytePesa',
        slug: 'bytepesa',
        category: 'ISP Billing',
        shortDescription: 'A billing and subscriber management system for ISPs.',
        hero: null,
      },
    ],
    capabilityItems: [],
    relatedCaseStudies: [
      {
        id: 'cs-1',
        title: 'BytePesa operations refresh',
        slug: 'bytepesa-operations-refresh',
        client: 'Eastlink',
        industry: 'ISP',
        summary: 'Service billing and operations were reworked into one system for a growing telecom business.',
      },
    ],
    seo: null,
  },
  {
    id: 'fb-aviation',
    name: 'Aviation',
    slug: 'aviation',
    shortDescription: 'Systems for bookings, flights and passenger operations.',
    businessContext: 'Aviation teams coordinate schedules, bookings, passengers and payments across operational touchpoints.',
    challengeHeadline: 'BOOKINGS AND\nOPERATIONS\nNEED CONNECTION.',
    challenge: 'Flight search, passenger handling and operational coordination require connected workflows rather than scattered tools.',
    systemDescription: 'Novaflow builds aviation platforms around bookings, passengers, payments and operational coordination.',
    systemItems: ['Bookings', 'Flights', 'Passengers', 'Payments', 'Operations'],
    status: 'published',
    order: 4,
    visual: null,
    mobileVisual: null,
    relatedProductItems: [
      {
        id: 'fp-apinai',
        name: 'Apinai Air',
        slug: 'apinai-air',
        category: 'Aviation',
        shortDescription: 'A digital platform for flight bookings and aviation operations.',
        hero: null,
      },
    ],
    capabilityItems: [],
    relatedCaseStudies: [],
    seo: null,
  },
  {
    id: 'fb-hospitality',
    name: 'Hospitality',
    slug: 'hospitality',
    shortDescription: 'Systems for reservations, guests and daily operations.',
    businessContext: 'Hospitality businesses coordinate guest bookings, service delivery and payments across properties and teams.',
    challengeHeadline: 'GUEST FLOW\nGETS\nCOMPLEX.',
    challenge: 'Reservations, guest services and operational tasks can become harder to manage when systems do not connect the full guest journey.',
    systemDescription: 'Novaflow can build hospitality systems around bookings, guest management, payments and operations.',
    systemItems: ['Bookings', 'Guests', 'Payments', 'Operations'],
    status: 'published',
    order: 5,
    visual: null,
    mobileVisual: null,
    relatedProductItems: [],
    capabilityItems: [],
    relatedCaseStudies: [],
    seo: null,
  },
  {
    id: 'fb-professional',
    name: 'Professional Services',
    slug: 'professional-services',
    shortDescription: 'Systems for clients, projects and service delivery.',
    businessContext: 'Professional services firms need clarity across clients, active work, billing and internal operations.',
    challengeHeadline: 'CLIENT WORK\nSPREADS\nACROSS TOOLS.',
    challenge: 'Project delivery, billing and client communication often become fragmented when there is no single operational view.',
    systemDescription: 'Novaflow builds business systems for client management, project coordination, billing and operations.',
    systemItems: ['Clients', 'Projects', 'Billing', 'Operations'],
    status: 'published',
    order: 6,
    visual: null,
    mobileVisual: null,
    relatedProductItems: [],
    capabilityItems: [],
    relatedCaseStudies: [],
    seo: null,
  },
];

export function getFallbackIndustries(): IndustryDetail[] {
  return FALLBACK_INDUSTRIES;
}

export function getFallbackIndustryBySlug(slug: string): IndustryDetail | null {
  return FALLBACK_INDUSTRIES.find((i) => i.slug === slug) ?? null;
}

export function getFallbackIndustryList(): Array<{ name: string; slug: string; order: number }> {
  return FALLBACK_INDUSTRIES.map(({ name, slug, order }) => ({ name, slug, order }));
}
